// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529011529_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Activity 2 months ago",
                            IsCancelled = false,
                            Latitude = 51.511716649999997,
                            Longitude = -0.1256611057818921,
                            Title = "Past Activity 1",
                            Venue = "The Lamb and Flag, 33, Rose Street, Seven Dials, Covent Garden, London, Greater London, England, WC2E 9EB, United Kingdom"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Activity 1 month ago",
                            IsCancelled = false,
                            Latitude = 48.861147299999999,
                            Longitude = 2.3380276870466599,
                            Title = "Past Activity 2",
                            Venue = "Louvre Museum, Rue Saint-Honoré, Quartier du Palais Royal, 1st Arrondissement, Paris, Ile-de-France, Metropolitan France, 75001, France"
                        },
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Activity 1 month in future",
                            IsCancelled = false,
                            Latitude = 51.496510900000004,
                            Longitude = -0.17600190725447445,
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = "44444444-4444-4444-4444-444444444444",
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Activity 2 months in future",
                            IsCancelled = false,
                            Latitude = 51.502936649999995,
                            Longitude = 0.0032029278126681844,
                            Title = "Future Activity 2",
                            Venue = "The O2"
                        },
                        new
                        {
                            Id = "55555555-5555-5555-5555-555555555555",
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Activity 3 months in future",
                            IsCancelled = false,
                            Latitude = 51.501778000000002,
                            Longitude = -0.053577,
                            Title = "Future Activity 3",
                            Venue = "The Mayflower"
                        },
                        new
                        {
                            Id = "66666666-6666-6666-6666-666666666666",
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Activity 4 months in future",
                            IsCancelled = false,
                            Latitude = 51.512146650000005,
                            Longitude = -0.10364680647106028,
                            Title = "Future Activity 4",
                            Venue = "The Blackfriar"
                        },
                        new
                        {
                            Id = "77777777-7777-7777-7777-777777777777",
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Activity 5 months in future",
                            IsCancelled = false,
                            Latitude = 51.523762900000001,
                            Longitude = -0.15847430000000001,
                            Title = "Future Activity 5",
                            Venue = "Sherlock Holmes Museum, 221b, Baker Street, Marylebone, London, Greater London, England, NW1 6XE, United Kingdom"
                        },
                        new
                        {
                            Id = "88888888-8888-8888-8888-888888888888",
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Activity 6 months in future",
                            IsCancelled = false,
                            Latitude = 51.543250499999999,
                            Longitude = -0.15197608174931165,
                            Title = "Future Activity 6",
                            Venue = "Roundhouse, Chalk Farm Road, Maitland Park, Chalk Farm, London Borough of Camden, London, Greater London, England, NW1 8EH, United Kingdom"
                        },
                        new
                        {
                            Id = "99999999-9999-9999-9999-999999999999",
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Activity 2 months ago",
                            IsCancelled = false,
                            Latitude = 51.5575525,
                            Longitude = -0.78140399999999999,
                            Title = "Future Activity 7",
                            Venue = "River Thames, England, United Kingdom"
                        },
                        new
                        {
                            Id = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Activity 8 months in future",
                            IsCancelled = false,
                            Latitude = 51.5575525,
                            Longitude = -0.78140399999999999,
                            Title = "Future Activity 8",
                            Venue = "River Thames, England, United Kingdom"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
